# Generated by Django 5.1.4 on 2025-01-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Categories',
        ),
    ]
